export const FETCH_USER = 'FETCH_USER'
export const FETCH_REPO = 'FETCH_REPO'
export const FETCH_USER_STARGAZERS = 'FETCH_USER_STARGAZERS'
export const FETCH_REPO_STARGAZERS = 'FETCH_REPO_STARGAZERS'

export const LOGGED_IN = 'LOGGED_IN'
export const LOG_OUT = 'LOG_OUT'

export const LOCALE_SWITCHED = 'LOCALE_SWITCHED'
export const SHOW_ERROR = 'SHOW_ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'

export const BAQEND_CONNECT = 'BAQEND_CONNECT'
export const BAQEND_CONNECTING = 'BAQEND_CONNECTING'
export const BAQEND_CONNECTED = 'BAQEND_CONNECTED'

export const ARTICLES_LOADED = 'ARTICLES_LOADED'

export const PRODUCTS_LOADED = 'PRODUCTS_LOADED'
export const PRODUCT_LOADED = 'PRODUCT_LOADED'
export const PRODUCT_COMPARISON_TOGGLED = 'PRODUCT_COMPARISON_TOGGLED'
